kargo:
  api:
    adminAccount:
      passwordHash: $2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm
      tokenSigningKey: iwishtowashmyirishwristwatch
      tokenTTL: 24h
  controller:
    logLevel: DEBUG
