api:
  secret:
    name: kargo-admin-secret
  adminAccount:
    tokenTTL: 24h
  host: kargo.7f000001.nip.io
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    annotations:
      '"nginx.ingress.kubernetes.io/force-ssl-redirect"': true
      '"nginx.ingress.kubernetes.io/ssl-passthrough"': true
controller:
  logLevel: DEBUG
