apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/christianh814/kargo-deployment-example
    targetRevision: main
    path: configs/kargo
  destination:
    #namespace: kargo
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #syncOptions:
    #- CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
