ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    hostNetwork: true
    nodeSelector:
      nginx: ingresshost
    service:
      externalTrafficPolicy: ""
      type: ClusterIP
    tolerations:
    - operator: Exists
